export { default as facebook } from './facebook.png';
export { default as line } from './line.png';
export { default as gmail } from './gmail.png';
export { default as bakery } from './bakery.png';
export { default as banner1 } from './7140944.png';
export { default as banner2 } from './7117437.png';
export { default as banner3 } from './7338165.png';
export { default as bakery_2 } from './bakery-2.png';
export { default as cookie} from './cookie.png';
export { default as cake} from './cake.png';
export { default as milk} from './milk.png';
export { default as teaCup} from './tea-cup.png';
export { default as drink} from './drink.png';
export { default as bubbleTea} from './bubble-tea.png';
export { default as user} from './user.png';